# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Auto deploy to NCP

#main branch가 push될 때마다 동작
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

#아래의 action을 수행할 runner의 os는 최신버전 ubuntu
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #소스코드(repo)를runner로 옮김. 서브모듈을 사용하므로 서브모듈 옵션도 추가
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.ACTION_TOKEN }}
    #명시한 환경으로 setup
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
      
    #현재 working dir 확인
    - name: check working dir
      run : ls -R
        
    # gradle setup & build
    - name: grant execute permission for gradlew
      run: |
        gradle wrapper
        chmod +x gradlew

    - name: gradle build
      run: ./gradlew clean build
    
    #build 결과 확인
    - name: Check build output
      run: ls -R /home/runner/work/URLumberjack
    
    #빌드한 jar파일을 도커 이미지로 빌드하고 도커 허브에 푸시
    - name: web docker build and push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_REPO }}/urlumberjack .
        docker push ${{ secrets.DOCKER_REPO }}/urlumberjack
    #NCP에 로그인해 docker image pull & run : https://github.com/appleboy/ssh-action
    - name : NCP login and docker image pull and run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.NCP_HOST }}
        username: ${{ secrets.NCP_USERNAME }}
        password: ${{ secrets.NCP_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p $ {{ secrets.DOCKER_PASSWARD }}
          sudo docker rm -f ${docker ps -p -a)
          sudo docker pull ${{ secrets.DOCKER_REPO }}/urlumberjack
          
